# Generated by Django 5.1.3 on 2024-11-23 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scoala', '0006_elev_restdeplata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FondRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('suma', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('created', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('anScolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoala.anscolar')),
                ('clasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoala.clasa')),
            ],
        ),
    ]
