# Generated by Django 5.1.3 on 2024-11-23 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiune', '0001_initial'),
        ('scoala', '0006_elev_restdeplata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fondrate',
            name='clasa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoala.clasa'),
        ),
    ]
