# Generated by Django 5.1.3 on 2024-11-24 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiune', '0006_cheltuiala'),
        ('scoala', '0007_alter_elev_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncasareDiversa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('suma', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('detalii', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('is_applied', models.BooleanField(default=False)),
                ('clasa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoala.clasa')),
            ],
        ),
    ]
