# Generated by Django 5.1.3 on 2024-11-30 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiune', '0007_incasarediversa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cheltuiala',
            options={'verbose_name_plural': 'Cheltuieli Diverse'},
        ),
        migrations.AlterModelOptions(
            name='fondrate',
            options={'verbose_name_plural': 'Fonduri de rate'},
        ),
        migrations.AlterModelOptions(
            name='incasare',
            options={'verbose_name_plural': 'Incasari'},
        ),
        migrations.AlterModelOptions(
            name='incasarediversa',
            options={'verbose_name_plural': 'Incasari Diverse'},
        ),
    ]
