# Generated by Django 5.1.3 on 2024-11-17 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clasa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('an', models.IntegerField()),
                ('anStart', models.IntegerField()),
                ('litera', models.CharField(max_length=1)),
                ('fond', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=50)),
                ('prenume', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Elev',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=50)),
                ('prenume', models.CharField(max_length=100)),
                ('clasa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoala.clasa')),
            ],
        ),
        migrations.AddField(
            model_name='clasa',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoala.profesor'),
        ),
    ]
