# Generated by Django 5.1.3 on 2024-11-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoala', '0002_elev_restdeplata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnScolar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anStart', models.IntegerField()),
                ('anFinal', models.IntegerField()),
            ],
        ),
    ]
