# Generated by Django 5.1.3 on 2024-11-23 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoala', '0004_alter_anscolar_anfinal_alter_anscolar_anstart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elev',
            old_name='restDePlata',
            new_name='contributie',
        ),
    ]
